In [96]:
import os
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score

#import pandas_profiling

In [2]:
os.chdir('C:\\Users\\User\\R-Markdowns\dataset_diabetes\dataset_diabetes')
os.listdir(os.getcwd())

['diabetic_data.csv', 'IDs_mapping.csv']

In [3]:
data = pd.read_csv("diabetic_data.csv")

In [ ]:
#data.profile_report(style={'full_width':True})

In [4]:
data["Readmitted?"] = (data.readmitted =="<30").astype("int")

In [5]:
data.head()

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,...,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted,Readmitted?
0,2278392,8222157,Caucasian,Female,[0-10),?,6,25,1,1,...,No,No,No,No,No,No,No,No,NO,0
1,149190,55629189,Caucasian,Female,[10-20),?,1,1,7,3,...,Up,No,No,No,No,No,Ch,Yes,>30,0
2,64410,86047875,AfricanAmerican,Female,[20-30),?,1,1,7,2,...,No,No,No,No,No,No,No,Yes,NO,0
3,500364,82442376,Caucasian,Male,[30-40),?,1,1,7,2,...,Up,No,No,No,No,No,Ch,Yes,NO,0
4,16680,42519267,Caucasian,Male,[40-50),?,1,1,7,1,...,Steady,No,No,No,No,No,Ch,Yes,NO,0

In [11]:
data = data[~data.discharge_disposition_id.isin([11,13,14,19,20,21])]

In [12]:
#compute for percentage of readmission
data["Readmitted?"].mean()
#this is an imbalance classification problem

0.11388824577474005

In [13]:
data = data.replace("?",np.nan)

In [15]:
data

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,...,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted,Readmitted?
0,2278392,8222157,Caucasian,Female,[0-10),NaN,6,25,1,1,...,No,No,No,No,No,No,No,No,NO,0
1,149190,55629189,Caucasian,Female,[10-20),NaN,1,1,7,3,...,Up,No,No,No,No,No,Ch,Yes,>30,0
2,64410,86047875,AfricanAmerican,Female,[20-30),NaN,1,1,7,2,...,No,No,No,No,No,No,No,Yes,NO,0
3,500364,82442376,Caucasian,Male,[30-40),NaN,1,1,7,2,...,Up,No,No,No,No,No,Ch,Yes,NO,0
4,16680,42519267,Caucasian,Male,[40-50),NaN,1,1,7,1,...,Steady,No,No,No,No,No,Ch,Yes,NO,0
5,35754,82637451,Caucasian,Male,[50-60),NaN,2,1,2,3,...,Steady,No,No,No,No,No,No,Yes,>30,0
6,55842,84259809,Caucasian,Male,[60-70),NaN,3,1,2,4,...,Steady,No,No,No,No,No,Ch,Yes,NO,0
7,63768,114882984,Caucasian,Male,[70-80),NaN,1,1,7,5,...,No,No,No,No,No,No,No,Yes,>30,0
8,12522,48330783,Caucasian,Female,[80-90),NaN,2,1,4,13,...,Steady,No,No,No,No,No,Ch,Yes,NO,0
9,15738,63555939,Caucasian,Female,[90-100),NaN,3,3,4,12,...,Steady,No,No,No,No,No,Ch,Yes,NO,0
10,28236,89869032,AfricanAmerican,Female,[40-50),NaN,1,1,7,9,...,Steady,No,No,No,No,No,No,Yes,>30,0
11,36900,77391171,AfricanAmerican,Male,[60-70),NaN,2,1,4,7,...,Steady,No,No,No,No,No,Ch,Yes,<30,1
12,40926,85504905,Caucasian,Female,[40-50),NaN,1,3,7,7,...,Down,No,No,No,No,No,Ch,Yes,<30,1
13,42570,77586282,Caucasian,Male,[80-90),NaN,1,6,7,10,...,Steady,No,No,No,No,No,No,Yes,NO,0
14,62256,49726791,AfricanAmerican,Female,[60-70),NaN,3,1,2,1,...,Steady,No,No,No,No,No,No,Yes,>30,0
15,73578,86328819,AfricanAmerican,Male,[60-70),NaN,1,3,7,12,...,Up,No,No,No,No,No,Ch,Yes,NO,0
16,77076,92519352,AfricanAmerican,Male,[50-60),NaN,1,1,7,4,...,Steady,No,No,No,No,No,Ch,Yes,<30,1
17,84222,108662661,Caucasian,Female,[50-60),NaN,1,1,7,3,...,No,No,No,No,No,No,No,Yes,NO,0
18,89682,107389323,AfricanAmerican,Male,[70-80),NaN,1,1,7,5,...,Steady,No,No,No,No,No,No,Yes,>30,0
19,148530,69422211,NaN,Male,[70-80),NaN,3,6,2,6,...,Steady,No,No,No,No,No,Ch,Yes,NO,0
20,150006,22864131,NaN,Female,[50-60),NaN,2,1,4,2,...,Down,No,No,No,No,No,Ch,Yes,NO,0
21,150048,21239181,NaN,Male,[60-70),NaN,2,1,4,2,...,Steady,No,No,No,No,No,Ch,Yes,NO,0
22,182796,63000108,AfricanAmerican,Female,[70-80),NaN,2,1,4,2,...,No,No,No,No,No,No,No,No,NO,0
23,183930,107400762,Caucasian,Female,[80-90),NaN,2,6,1,11,...,No,No,No,No,No,No,No,No,>30,0
24,216156,62718876,AfricanAmerican,Female,[70-80),NaN,3,1,2,3,...,Steady,No,No,No,No,No,Ch,Yes,NO,0
25,221634,21861756,Other,Female,[50-60),NaN,1,1,7,1,...,No,No,No,No,No,No,No,Yes,NO,0
26,236316,40523301,Caucasian,Male,[80-90),NaN,1,3,7,6,...,No,No,No,No,No,No,Ch,Yes,NO,0
27,248916,115196778,Caucasian,Female,[50-60),NaN,1,1,1,2,...,Steady,No,No,No,No,No,No,Yes,>30,0
28,250872,41606064,Caucasian,Male,[20-30),NaN,2,1,2,10,...,Down,No,No,No,No,No,Ch,Yes,>30,0
29,252822,18196434,Caucasian,Female,[80-90),NaN,1,2,7,5,...,No,No,No,No,No,No,Ch,Yes,>30,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101735,443739044,106595208,Caucasian,Male,[70-80),NaN,2,6,7,6,...,Up,No,No,No,No,No,Ch,Yes,NO,0
101736,443739152,90751788,Caucasian,Female,[60-70),NaN,1,3,7,8,...,Steady,No,No,No,No,No,No,Yes,>30,0
101737,443775086,125764160,Caucasian,Female,[40-50),NaN,3,1,1,4,...,Steady,No,No,No,No,No,Ch,Yes,NO,0
101738,443775482,95780439,Caucasian,Male,[70-80),NaN,1,1,7,1,...,No,No,No,No,No,No,No,Yes,NO,0
101739,443775740,30656952,AfricanAmerican,Male,[70-80),NaN,1,1,7,1,...,Steady,No,No,No,No,No,No,Yes,NO,0
101740,443778398,134647673,Caucasian,Male,[40-50),NaN,3,1,1,1,...,Steady,No,No,No,No,No,Ch,Yes,NO,0
101741,443787128,58160520,AfricanAmerican,Male,[90-100),NaN,1,3,7,4,...,No,No,No,No,No,No,No,No,NO,0
101742,443787512,52419276,Caucasian,Male,[70-80),NaN,2,6,2,4,...,Steady,No,No,No,No,No,Ch,Yes,NO,0
101744,443793992,43686936,Caucasian,Female,[80-90),NaN,1,1,7,1,...,No,No,No,No,No,No,No,No,NO,0
101745,443797076,183766055,Caucasian,Male,[50-60),NaN,2,1,1,3,...,No,No,No,No,No,No,Ch,Yes,NO,0
101746,443797298,89955270,Caucasian,Male,[70-80),NaN,1,1,7,4,...,No,No,No,No,No,No,No,Yes,<30,1
101747,443804570,33230016,Caucasian,Female,[70-80),NaN,1,22,7,8,...,Steady,No,No,No,No,No,No,Yes,>30,0
101748,443811536,189481478,Caucasian,Female,[40-50),NaN,1,4,7,14,...,Down,No,No,No,No,No,Ch,Yes,>30,0
101749,443816024,106392411,Caucasian,Female,[70-80),NaN,3,6,1,3,...,Steady,No,No,No,No,No,Ch,Yes,NO,0
101750,443824292,138784172,Caucasian,Female,[80-90),NaN,3,1,1,3,...,Down,No,No,No,No,No,Ch,Yes,<30,1
101751,443835140,175326800,Caucasian,Male,[70-80),NaN,3,6,1,13,...,Up,No,No,No,No,No,Ch,Yes,NO,0
101752,443835512,139605341,Other,Female,[40-50),NaN,3,1,1,3,...,Steady,No,No,No,No,No,Ch,Yes,NO,0
101753,443841992,184875899,Other,Male,[40-50),NaN,1,1,7,13,...,Down,No,No,No,No,No,Ch,Yes,NO,0
101754,443842016,183087545,Caucasian,Female,[70-80),NaN,1,1,7,9,...,Steady,No,No,No,No,No,Ch,Yes,>30,0
101755,443842022,188574944,Other,Female,[40-50),NaN,1,1,7,14,...,Up,No,No,No,No,No,Ch,Yes,>30,0
101756,443842070,140199494,Other,Female,[60-70),NaN,1,1,7,2,...,Steady,No,No,No,No,No,No,Yes,>30,0
101757,443842136,181593374,Caucasian,Female,[70-80),NaN,1,1,7,5,...,Steady,No,No,No,No,No,No,Yes,NO,0
101758,443842340,120975314,Caucasian,Female,[80-90),NaN,1,1,7,5,...,Up,No,No,No,No,No,Ch,Yes,NO,0
101759,443842778,86472243,Caucasian,Male,[80-90),NaN,1,1,7,1,...,Up,No,No,No,No,No,Ch,Yes,NO,0
101760,443847176,50375628,AfricanAmerican,Female,[60-70),NaN,1,1,7,6,...,Down,No,No,No,No,No,Ch,Yes,>30,0
101761,443847548,100162476,AfricanAmerican,Male,[70-80),NaN,1,3,7,3,...,Down,No,No,No,No,No,Ch,Yes,>30,0
101762,443847782,74694222,AfricanAmerican,Female,[80-90),NaN,1,4,5,5,...,Steady,No,No,No,No,No,No,Yes,NO,0
101763,443854148,41088789,Caucasian,Male,[70-80),NaN,1,1,7,1,...,Down,No,No,No,No,No,Ch,Yes,NO,0
101764,443857166,31693671,Caucasian,Female,[80-90),NaN,2,3,7,10,...,Up,No,No,No,No,No,Ch,Yes,NO,0
101765,443867222,175429310,Caucasian,Male,[70-80),NaN,1,1,7,6,...,No,No,No,No,No,No,No,No,NO,0

In [17]:
data.isnull().sum()

encounter_id                    0
patient_nbr                     0
race                         2234
gender                          0
age                             0
weight                      96218
admission_type_id               0
discharge_disposition_id        0
admission_source_id             0
time_in_hospital                0
payer_code                  39398
medical_specialty           48616
num_lab_procedures              0
num_procedures                  0
num_medications                 0
number_outpatient               0
number_emergency                0
number_inpatient                0
diag_1                         20
diag_2                        356
diag_3                       1419
number_diagnoses                0
max_glu_serum                   0
A1Cresult                       0
metformin                       0
repaglinide                     0
nateglinide                     0
chlorpropamide                  0
glimepiride                     0
acetohexamide                   0
glipizide                       0
glyburide                       0
tolbutamide                     0
pioglitazone                    0
rosiglitazone                   0
acarbose                        0
miglitol                        0
troglitazone                    0
tolazamide                      0
examide                         0
citoglipton                     0
insulin                         0
glyburide-metformin             0
glipizide-metformin             0
glimepiride-pioglitazone        0
metformin-rosiglitazone         0
metformin-pioglitazone          0
change                          0
diabetesMed                     0
readmitted                      0
Readmitted?                     0
dtype: int64

In [19]:
#create new category for unknown values in race, payer_code, and medical_speciality
data["race"] = data["race"].fillna("UNKNOWN")
data["payer_code"] = data["payer_code"].fillna("UNKNOWN")
data["medical_specialty"] = data["medical_specialty"].fillna("UNKNOWN")

In [20]:
data.isnull().sum()

encounter_id                    0
patient_nbr                     0
race                            0
gender                          0
age                             0
weight                      96218
admission_type_id               0
discharge_disposition_id        0
admission_source_id             0
time_in_hospital                0
payer_code                      0
medical_specialty               0
num_lab_procedures              0
num_procedures                  0
num_medications                 0
number_outpatient               0
number_emergency                0
number_inpatient                0
diag_1                         20
diag_2                        356
diag_3                       1419
number_diagnoses                0
max_glu_serum                   0
A1Cresult                       0
metformin                       0
repaglinide                     0
nateglinide                     0
chlorpropamide                  0
glimepiride                     0
acetohexamide                   0
glipizide                       0
glyburide                       0
tolbutamide                     0
pioglitazone                    0
rosiglitazone                   0
acarbose                        0
miglitol                        0
troglitazone                    0
tolazamide                      0
examide                         0
citoglipton                     0
insulin                         0
glyburide-metformin             0
glipizide-metformin             0
glimepiride-pioglitazone        0
metformin-rosiglitazone         0
metformin-pioglitazone          0
change                          0
diabetesMed                     0
readmitted                      0
Readmitted?                     0
dtype: int64

In [29]:
#medical specialty has a lot of values, think of what to do with it
#can change those not in top 10 to others
top_med = np.array(data.medical_specialty.value_counts().sort_values(ascending=False).index)[:10]
data.medical_specialty[~data.medical_specialty.isin(top_med)] = "Others"
data.head()

C:\Users\User\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,...,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted,Readmitted?
0,2278392,8222157,Caucasian,Female,[0-10),NaN,6,25,1,1,...,No,No,No,No,No,No,No,No,NO,0
1,149190,55629189,Caucasian,Female,[10-20),NaN,1,1,7,3,...,Up,No,No,No,No,No,Ch,Yes,>30,0
2,64410,86047875,AfricanAmerican,Female,[20-30),NaN,1,1,7,2,...,No,No,No,No,No,No,No,Yes,NO,0
3,500364,82442376,Caucasian,Male,[30-40),NaN,1,1,7,2,...,Up,No,No,No,No,No,Ch,Yes,NO,0
4,16680,42519267,Caucasian,Male,[40-50),NaN,1,1,7,1,...,Steady,No,No,No,No,No,Ch,Yes,NO,0

In [30]:
data.medical_specialty.value_counts()

UNKNOWN                       48616
InternalMedicine              14237
Others                         8199
Emergency/Trauma               7419
Family/GeneralPractice         7252
Cardiology                     5279
Surgery-General                3059
Nephrology                     1539
Orthopedics                    1392
Orthopedics-Reconstructive     1230
Radiologist                    1121
Name: medical_specialty, dtype: int64

In [32]:
##one-hot encoding for variables admission_type_id, discharge_disposition_id, admission_source_id

category_var = ["admission_type_id", "discharge_disposition_id", "admission_source_id"]
data[category_var] = data[category_var].astype("str")

In [45]:
np.array(data.columns)[2:data.shape[1]-2]

array(['race', 'gender', 'age', 'weight', 'admission_type_id',
       'discharge_disposition_id', 'admission_source_id',
       'time_in_hospital', 'payer_code', 'medical_specialty',
       'num_lab_procedures', 'num_procedures', 'num_medications',
       'number_outpatient', 'number_emergency', 'number_inpatient',
       'diag_1', 'diag_2', 'diag_3', 'number_diagnoses', 'max_glu_serum',
       'A1Cresult', 'metformin', 'repaglinide', 'nateglinide',
       'chlorpropamide', 'glimepiride', 'acetohexamide', 'glipizide',
       'glyburide', 'tolbutamide', 'pioglitazone', 'rosiglitazone',
       'acarbose', 'miglitol', 'troglitazone', 'tolazamide', 'examide',
       'citoglipton', 'insulin', 'glyburide-metformin',
       'glipizide-metformin', 'glimepiride-pioglitazone',
       'metformin-rosiglitazone', 'metformin-pioglitazone', 'change',
       'diabetesMed'], dtype=object)

In [41]:
data.shape[1]

51

In [49]:
print(len(data), data.patient_nbr.nunique(), data.encounter_id.nunique())

99343 69990 99343

In [54]:
cols_num = ['time_in_hospital','num_lab_procedures', 'num_procedures', 'num_medications',
       'number_outpatient', 'number_emergency', 'number_inpatient','number_diagnoses']
cols_cat = ['race', 'gender', 
       'max_glu_serum', 'A1Cresult',
       'metformin', 'repaglinide', 'nateglinide', 'chlorpropamide',
       'glimepiride', 'acetohexamide', 'glipizide', 'glyburide', 'tolbutamide',
       'pioglitazone', 'rosiglitazone', 'acarbose', 'miglitol', 'troglitazone',
       'tolazamide', 'insulin',
       'glyburide-metformin', 'glipizide-metformin',
       'glimepiride-pioglitazone', 'metformin-rosiglitazone',
       'metformin-pioglitazone', 'change', 'diabetesMed','payer_code']

cols_cat_num = ['admission_type_id', 'discharge_disposition_id', 'admission_source_id']

data[cols_cat_num] = data[cols_cat_num].astype('str')

In [57]:
data_new =  pd.get_dummies(data[cols_cat + cols_cat_num + ['medical_specialty']],drop_first = True)

In [59]:
data = pd.concat([data,data_new],axis=1)

In [63]:
data.age = data.age.replace({'[0-10)':5, 
          '[10-20)':15, 
          '[20-30)':25, 
          '[30-40)':35, 
          '[40-50)':45, 
          '[50-60)':55,
          '[60-70)':65, 
          '[70-80)':75, 
          '[80-90)':85, 
          '[90-100)':95})

In [ ]:
#or maybe drop weight na lang
data['has_weight'] = data.weight.notnull().astype('int')

## what to with repeating patient numbers??

In [78]:
## removing raw eright column
cols_all_cat = np.array(data.columns)
cols_all_cat = np.delete(cols_all_cat,5)

In [88]:
cols_extra = ['age','has_weight']
cols = cols_num + list(cols_all_cat) + cols_extra

### Create filtered column dataset

In [89]:
final = data[cols + ['Readmitted?']]

In [91]:
final.gender.value_counts()

Female             53454
Male               45886
Unknown/Invalid        3
Name: gender, dtype: int64

In [95]:
final = final[final.gender!="Unknown/Invalid"]

In [117]:
y = final["Readmitted?"]
x = final.drop(["Readmitted?","readmitted","weight",'encounter_id', 'patient_nbr'],axis=1)

In [108]:
x.columns

Index(['time_in_hospital', 'num_lab_procedures', 'num_procedures',
       'num_medications', 'number_outpatient', 'number_emergency',
       'number_inpatient', 'number_diagnoses', 'encounter_id', 'patient_nbr',
       ...
       'medical_specialty_Orthopedics',
       'medical_specialty_Orthopedics-Reconstructive',
       'medical_specialty_Others', 'medical_specialty_Radiologist',
       'medical_specialty_Surgery-General', 'medical_specialty_UNKNOWN',
       'has_weight', 'age', 'has_weight', 'Readmitted?'],
      dtype='object', length=195)

In [119]:
x.head()

,time_in_hospital,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,number_diagnoses,race,gender,...,medical_specialty_Nephrology,medical_specialty_Orthopedics,medical_specialty_Orthopedics-Reconstructive,medical_specialty_Others,medical_specialty_Radiologist,medical_specialty_Surgery-General,medical_specialty_UNKNOWN,has_weight,age,has_weight
0,1,41,0,1,0,0,0,1,Caucasian,Female,...,0,0,0,1,0,0,0,0,5,0
1,3,59,0,18,0,0,0,9,Caucasian,Female,...,0,0,0,0,0,0,1,0,15,0
2,2,11,5,13,2,0,1,6,AfricanAmerican,Female,...,0,0,0,0,0,0,1,0,25,0
3,2,44,1,16,0,0,0,7,Caucasian,Male,...,0,0,0,0,0,0,1,0,35,0
4,1,51,0,8,0,0,0,5,Caucasian,Male,...,0,0,0,0,0,0,1,0,45,0

## Logistic Regression

In [118]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=0)
logit = LogisticRegression(fit_intercept=True, penalty='l1')
logit.fit(X_train, y_train)

ValueError: could not convert string to float: 'Yes'

In [ ]:
logit_pred = logit.predict(X_test)
pd.crosstab(pd.Series(y_test, name = 'Actual'), pd.Series(logit_pred, name = 'Predict'), margins = True)

In [ ]:
from sklearn.metrics import accuracy_score, precision_score, recall_score
print("Accuracy is {0:.2f}".format(accuracy_score(y_test, logit_pred)))
print("Precision is {0:.2f}".format(precision_score(y_test, logit_pred)))
print("Recall is {0:.2f}".format(recall_score(y_test, logit_pred)))

Typically, it is better to balance the data in some way to give the positives more weight. There are 3 strategies that are typically utilized
sub-sample the more dominant class:
- use a random subset of the negatives
- over-sample the imbalanced class: use the same positive samples multiple times
- create synthetic positive data